version: '2.4'

services:
  conductor-server:
    image: conductor:server
    networks:
      - internal
    ports:
      - 8080:8080
    volumes:
      - ./server/config/config.properties:/app/config/config.properties
    links:
      - elasticsearch:es
      - redis:r1
    depends_on:
      elasticsearch:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  conductor-ui:
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    image: conductor:ui
    build:
      context: ../
      dockerfile: docker/ui/Dockerfile
    networks:
      - internal
    ports:
      - 5000:5000
    links:
      - conductor-server

  redis:
    image: redis:6
    networks:
      - internal
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  dyno1:
    image: 782253790350.dkr.ecr.us-east-1.amazonaws.com/bridge/conductor/dynomite:latest
    networks:
      - internal
    volumes:
      - ./server/dynomite/redis_docker.yml:/dynomite/conf/redis_bridge.yml
    ports:
      - 8102:8102
      - 22222:22222
      - 8101:8101
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  # https://www.elastic.co/guide/en/elasticsearch/reference/6.8/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.11
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - internal
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9300'
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

volumes:
  es-data:
    driver: local
  redis-data:
    driver: local

networks:
  internal:
